
package org.apereo.cas;

import org.apereo.cas.ticket.registry.IgniteTicketRegistryWithEncryptionTests;
import org.apereo.cas.ticket.registry.IgniteTicketRegistryWithoutEncryptionTests;

import org.junit.platform.suite.api.SelectClasses;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@SelectClasses({
    IgniteTicketRegistryWithEncryptionTests.class,
    IgniteTicketRegistryWithoutEncryptionTests.class
})
public class AllTestsSuite {
}
