
package org.apereo.cas;

import org.apereo.cas.ticket.registry.IgniteTicketRegistryTests;

import org.junit.platform.suite.api.SelectClasses;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@SelectClasses(IgniteTicketRegistryTests.class)
public class AllTestsSuite {
}
