
package org.apereo.cas;

import org.apereo.cas.ticket.registry.IgniteTicketRegistryWithEncryptionTests;
import org.apereo.cas.ticket.registry.IgniteTicketRegistryWithoutEncryptionTests;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@RunWith(Suite.class)
@Suite.SuiteClasses({
    IgniteTicketRegistryWithEncryptionTests.class,
    IgniteTicketRegistryWithoutEncryptionTests.class
})
public class AllTestsSuite {
}
