package org.apereo.cas.gradle

enum TestCategories {
    ActiveDirectory(false, true),
    ActuatorEndpoint(true, true),
    AmazonWebServices(true, true),
    AMQP(false, true),
    ApacheTomcat(true, true),
    Attributes(true, true),
    AttributeRelease(true, true),
    AttributeRepository(true, true),
    Audits(true, true),
    Authentication(true, true),
    AuthenticationHandler(true, true),
    AuthenticationPolicy(true, true),
    AuthenticationMetadata(true, true),
    AuthenticationThrottling(false, true),
    Authorization(true, true),
    Azure(false, true),
    CAS(true, true),
    CasConfiguration(true, true),
    Cassandra(false, true),
    Cipher(true, true),
    Consent(true, true),
    Cookie(true, true),
    Delegation(true, true),
    DuoSecurity(true, true),
    DynamoDb(false, true),
    Elastic(true, true),
    ExpirationPolicy(true),
    Events(true, true),
    FileSystem(false, true),
    GCP(false, true),
    GeoLocation(true, true),
    Git(true, true),
    Groovy(true, true),
    GroovyAuthentication(true, true),
    GroovyMfa(true, true),
    GroovyServices(true, true),
    Grouper(true, true),
    Hazelcast(false, true),
    Hibernate(false, true),
    Ignite(false, true),
    Impersonation(true, true),
    InfluxDb(true, true),
    JDBC(false, true),
    JDBCMFA(false, true),
    JDBCAuthentication(false, true),
    JMX(true, true),
    Kafka(true, true),
    Pulsar(true, true),
    LdapAttributes(true, true),
    LdapAuthentication(false, true),
    Ldap(false, true),
    LdapServices(false, true),
    LdapRepository(false, true),
    Logout(true, true),
    Mail(true, true),
    MariaDb(false, true),
    Memcached(false, true),
    Metrics(true, true),
    MFA(true, true),
    MFAProvider(true, true),
    MFATrigger(true, true),
    MFATrustedDevices(false, true),
    MongoDb(false, true),
    MongoDbMFA(false, true),
    MsSqlServer(false, true),
    MySQL(false, true),
    Native(true, true),
    OAuth(true, true),
    OAuthToken(true, true),
    OAuthWeb(false, true),
    OIDC(true, true),
    OIDCWeb(true, true),
    OIDCAttributes(true, true),
    OIDCAuthentication(true, true),
    OIDCServices(true, true),
    Oracle(false, true),
    PasswordOps(true, true),
    Postgres(false, true),
    Radius(true, true),
    Redis(false, true),
    RegisteredService(true, true),
    RestfulApi(false, true),
    RestfulApiAuthentication(true, true),
    SAML(true, true),
    SAML1(true, true),
    SAML2(false, true),
    SAML2Web(false, true),
    SAMLMetadata(true, true),
    SAMLServiceProvider(true, true),
    SAMLLogout(true, true),
    SAMLAttributes(true, true),
    SAMLResponse(false, true),
    SCIM(true, true),
    SHELL(true, true),
    Simple(true, true),
    SMS(true, true),
    Spnego(true, true),
    Syncope(true, true),
    Tickets(true, true),
    UMA(true, true),
    Utility(true, true),
    Web(true, true),
    WebApp(true, true),
    Webflow(true, true),
    WebflowActions(true, true),
    WebflowAccountActions(true, true),
    WebflowServiceActions(true, true),
    WebflowAuthenticationActions(true, true),
    WebflowConfig(true, true),
    WebflowMfaConfig(true, true),
    WebflowEvents(true, true),
    WebflowMfaActions(true),
    WSFederation(true, true),
    X509(true, true),
    ZooKeeper(true, true)

    final boolean parallelEnabled
    final boolean ptsEnabled

    TestCategories() {
        this(false, false)
    }

    TestCategories(final boolean parallelEnabled) {
        this(parallelEnabled, false)
    }

    TestCategories(final boolean parallelEnabled, final boolean ptsEnabled) {
        this.parallelEnabled = parallelEnabled
        this.ptsEnabled = ptsEnabled
    }
}

