
package org.apereo.cas;

import org.apereo.cas.adaptors.generic.remote.RemoteAddressAuthenticationHandlerTests;
import org.apereo.cas.adaptors.generic.remote.RemoteAddressCredentialTests;

import org.junit.platform.suite.api.SelectClasses;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@SelectClasses({
    RemoteAddressCredentialTests.class,
    RemoteAddressAuthenticationHandlerTests.class
})
public class AllTestsSuite {
}
