
package org.apereo.cas;

import org.apereo.cas.adaptors.generic.remote.RemoteAddressCredentialTests;
import org.apereo.cas.adaptors.generic.remote.RemoteAddressAuthenticationHandlerTests;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@RunWith(Suite.class)
@Suite.SuiteClasses({
    RemoteAddressCredentialTests.class,
    RemoteAddressAuthenticationHandlerTests.class
})
public class AllTestsSuite {
}
