apply plugin: "org.apereo.cas.project-conventions"

description = "Registers CAS configuration and discovery clients with HashiCorp Consul for Spring Cloud deployments."
ext {
    publishMetadata = true
    projectMetadata = [
            category: "Integrations",
            title: "Consul Discovery Client"
    ]
}
dependencies {
    api project(":api:cas-server-core-api-util")
    implementation libraries.springcloudconsul
    provided project(":core:cas-server-core-util")
    provided project(":core:cas-server-core-configuration")
}
