
package org.apereo.cas;

import org.apereo.cas.support.x509.rest.X509RestHttpRequestHeaderCredentialFactoryTests;
import org.apereo.cas.support.x509.rest.X509RestMultipartBodyCredentialFactoryTests;
import org.apereo.cas.support.x509.rest.X509RestTlsClientCertCredentialFactoryTests;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@RunWith(Suite.class)
@Suite.SuiteClasses({
    X509RestHttpRequestHeaderCredentialFactoryTests.class,
    X509RestMultipartBodyCredentialFactoryTests.class,
    X509RestTlsClientCertCredentialFactoryTests.class

})
public class AllTestsSuite {
}
