
package org.apereo.cas;

import org.apereo.cas.support.x509.rest.X509RestHttpRequestHeaderCredentialFactoryTests;
import org.apereo.cas.support.x509.rest.X509RestMultipartBodyCredentialFactoryTests;

import org.junit.platform.suite.api.SelectClasses;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@SelectClasses({
    X509RestHttpRequestHeaderCredentialFactoryTests.class,
    X509RestMultipartBodyCredentialFactoryTests.class
})
public class AllTestsSuite {
}
