
package org.apereo.cas;

import org.apereo.cas.services.GroovySurrogateRegisteredServiceAccessStrategyTests;
import org.apereo.cas.services.SurrogateRegisteredServiceAccessStrategyTests;

import org.junit.platform.suite.api.SelectClasses;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@SelectClasses({
    GroovySurrogateRegisteredServiceAccessStrategyTests.class,
    SurrogateRegisteredServiceAccessStrategyTests.class
})
public class AllTestsSuite {
}
