
package org.apereo.cas;

import org.apereo.cas.authentication.PasswordlessTokenAuthenticationHandlerTests;
import org.apereo.cas.impl.account.GroovyPasswordlessUserAccountStoreTests;
import org.apereo.cas.impl.account.RestfulPasswordlessUserAccountStoreTests;
import org.apereo.cas.impl.token.RestfulPasswordlessTokenRepositoryTests;
import org.apereo.cas.web.flow.DisplayBeforePasswordlessAuthenticationActionTests;
import org.apereo.cas.web.flow.PrepareForPasswordlessAuthenticationActionTests;

import org.junit.platform.suite.api.SelectClasses;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@SelectClasses({
    RestfulPasswordlessTokenRepositoryTests.class,
    RestfulPasswordlessUserAccountStoreTests.class,
    GroovyPasswordlessUserAccountStoreTests.class,
    DisplayBeforePasswordlessAuthenticationActionTests.class,
    PrepareForPasswordlessAuthenticationActionTests.class,
    PasswordlessTokenAuthenticationHandlerTests.class
})
public class AllTestsSuite {
}
