codecov:
  max_report_age: off
  strict_yaml_branch: master

coverage:
  round: up
  range: "70...100"
  precision: 5
  status:
    project:
      default:
        # basic
        target: 70%
        threshold: 0%
        base: auto 
        flags: 
          - unit
        paths: 
          - "src"
       # advanced
        branches: 
          - master
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false
