
package org.apereo.cas;

import org.apereo.cas.pm.web.flow.actions.HandlePasswordExpirationWarningMessagesActionTests;
import org.apereo.cas.pm.web.flow.actions.InitPasswordResetActionTests;
import org.apereo.cas.pm.web.flow.actions.SendPasswordResetInstructionsActionTests;
import org.apereo.cas.pm.web.flow.actions.VerifyPasswordResetRequestActionTests;
import org.apereo.cas.pm.web.flow.actions.VerifySecurityQuestionsActionTests;

import org.junit.platform.runner.JUnitPlatform;
import org.junit.platform.suite.api.SelectClasses;
import org.junit.runner.RunWith;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@SelectClasses({
    VerifySecurityQuestionsActionTests.class,
    SendPasswordResetInstructionsActionTests.class,
    InitPasswordResetActionTests.class,
    VerifyPasswordResetRequestActionTests.class,
    HandlePasswordExpirationWarningMessagesActionTests.class
})
@RunWith(JUnitPlatform.class)
public class AllTestsSuite {
}
