#! /bin/bash
service cas stop
rm -rf ~/cas1/logs/*
rm -rf ~/cas1/webapps/cas*
rm -rf ~/cas1/temp/*
rm -rf ~/cas1/work/*
rm -f ~/cas1/conf/Catalina/localhost/cas.xml

echo -e "Compile Modules? [n]: \c"
read ext
if [ "$ext" == "y" -o "$ext" == "Y" ]; then
	list=`find ~/cas -maxdepth 1 -name cas-* -type d`
	for fn in $list
	do
		if [ "$fn" != "/root/cas/cas-server-cc" ]; then
			echo -e "Compile $fn ? [n]: \c"
			read ext
			if [ "$ext" == "y" -o "$ext" == "Y" ]; then
				cd $fn
				mvn package install
			fi
		fi
	done
fi
echo -e "Compile CAS CC? [Y]: \c"
read ext
if [ -z $ext ] || [ "$ext" == "Y" ] || [ "$ext" == "y" ]; then
	cd ~/cas/cas-server-cc
	mvn clean package
fi
echo -e "Start CAS? [Y]: \c"
read ext
if [ -z $ext ] || [ "$ext" == "Y" ] || [ "$ext" == "y" ]; then	
	cp ~/cas/cas-server-cc/target/cas.war ~/cas1/webapps/cas.war
	service cas start
fi
echo -e "Start java Log Viewer? [Y]: \c"
read ext
if [ -z $ext ] || [ "$ext" == "Y" ] || [ "$ext" == "y" ]; then
	java  -jar ~/JLogTailer.jar &
fi
