/*
 * Copyright 2004 The JA-SIG Collaborative. All rights reserved. See license distributed with this file and available online at
 * http://www.uportal.org/license.html
 */
package org.jasig.cas.ticket.factory;

import org.jasig.cas.authentication.principal.Principal;
import org.jasig.cas.ticket.CasAttributes;
import org.jasig.cas.ticket.Ticket;

/**
 * Strategy interface to create different type of <code>Ticket</code>s.
 * 
 * @author Scott Battaglia
 * @version $Id$
 * @see org.jasig.cas.ticket.Ticket
 * @see org.jasig.cas.ticket.CasAttributes
 */
public interface TicketCreator {

    /**
     * Create a new ticket instance from the initial parameters.
     * 
     * @param request The initial parameters.
     * @param ticketId The id to assign to the ticket
     * @param grantingTicket The parent ticket of the ticket we want to create.
     * @return The new immutable ticket.
     */
    public Ticket createTicket(Principal principal, CasAttributes request, Ticket grantingTicket);
    
    /**
     * Determine if a class is supported by this helper.
     * 
     * @param clazz the class we wish to support
     * @return true if the class is one this helper supports, otherwise false.
     */
    public boolean supports(Class clazz);

    /**
     * Retrieve the prefix to attach to any ticket generated by this helper.
     * 
     * @return the prefix of the ticket id.
     */
    public String getPrefix();
}