
package org.apereo.cas;

import org.apereo.cas.adaptors.radius.authentication.handler.support.RadiusAuthenticationHandlerTests;
import org.apereo.cas.config.RadiusConfigurationTests;

import org.junit.platform.suite.api.SelectClasses;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@SelectClasses({
    RadiusConfigurationTests.class,
    RadiusAuthenticationHandlerTests.class
})
public class AllTestsSuite {
}
