
package org.apereo.cas;

import org.apereo.cas.authentication.surrogate.SurrogateCouchDbProfileAuthenticationServiceTests;
import org.apereo.cas.authentication.surrogate.SurrogateCouchDbAuthenticationTests;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@RunWith(Suite.class)
@Suite.SuiteClasses({
    SurrogateCouchDbProfileAuthenticationServiceTests.class,
    SurrogateCouchDbAuthenticationTests.class
})
public class AllTestsSuite {
}
