
package org.apereo.cas;

import org.apereo.cas.configuration.CasConfigurationPropertiesTests;
import org.apereo.cas.configuration.CommaSeparatedStringToThrowablesConverterTests;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@RunWith(Suite.class)
@Suite.SuiteClasses({
    CommaSeparatedStringToThrowablesConverterTests.class,
    CasConfigurationPropertiesTests.class
})
public class AllTestsSuite {
}
