
package org.apereo.cas;

import org.apereo.cas.configuration.CasConfigurationPropertiesTests;
import org.apereo.cas.configuration.CommaSeparatedStringToThrowablesConverterTests;

import org.junit.platform.suite.api.SelectClasses;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@SelectClasses({
    CommaSeparatedStringToThrowablesConverterTests.class,
    CasConfigurationPropertiesTests.class
})
public class AllTestsSuite {
}
