package org.apereo.cas.configuration.model.support.wsfed;

import org.apereo.cas.configuration.model.core.util.EncryptionJwtSigningJwtCryptographyProperties;
import org.springframework.boot.context.properties.NestedConfigurationProperty;

import java.io.Serializable;

/**
 * This is {@link WsFederationProperties}.
 *
 * @author Misagh Moayyed
 * @since 5.1.0
 */
public class WsFederationProperties implements Serializable {
    private static final long serialVersionUID = -8679379856243224647L;

    /**
     * Settings related to the wed-fed identity provider.
     */
    private IdentityProvider idp = new IdentityProvider();
    /**
     * Settings related to the we-fed security token service.
     */
    private SecurityTokenService sts = new SecurityTokenService();

    public IdentityProvider getIdp() {
        return idp;
    }

    public void setIdp(final IdentityProvider idp) {
        this.idp = idp;
    }

    public SecurityTokenService getSts() {
        return sts;
    }

    public void setSts(final SecurityTokenService sts) {
        this.sts = sts;
    }

    public static class IdentityProvider implements Serializable {
        private static final long serialVersionUID = 5190493517277610788L;
        /**
         * At this point, by default security token service’s endpoint operate using a single
         * realm configuration and identity provider configuration is only able to recognize and request tokens for a single realm.
         * Registration of clients need to ensure this value is matched.
         */
        private String realm = "urn:org:apereo:cas:ws:idp:realm-CAS";
        /**
         * Realm name.
         */
        private String realmName = "CAS";

        public String getRealm() {
            return realm;
        }

        public void setRealm(final String realm) {
            this.realm = realm;
        }

        public String getRealmName() {
            return realmName;
        }

        public void setRealmName(final String realmName) {
            this.realmName = realmName;
        }
    }

    public static class SecurityTokenService implements Serializable {
        private static final long serialVersionUID = -1155140161252595793L;
        /**
         * When generating a SAML token, indicates the subject name-id format to use.
         */
        private String subjectNameIdFormat = "unspecified";
        /**
         * Whether tokens generated by STS should encrypted.
         */
        private boolean encryptTokens = true;

        /**
         * Keystore path used to sign tokens.
         */
        private String signingKeystoreFile;
        /**
         * Keystore password used to sign tokens.
         */
        private String signingKeystorePassword;
        /**
         * Keystore path used to encrypt tokens.
         */
        private String encryptionKeystoreFile;
        /**
         * Keystore password used to encrypt tokens.
         */
        private String encryptionKeystorePassword;

        /**
         * Crypto settings used to secure calls between the idp and the sts.
         */
        @NestedConfigurationProperty
        private EncryptionJwtSigningJwtCryptographyProperties crypto = new EncryptionJwtSigningJwtCryptographyProperties();

        /**
         * Realm definition settings that define this CAS server.
         */
        private RealmDefinition realm = new RealmDefinition();

        public EncryptionJwtSigningJwtCryptographyProperties getCrypto() {
            return crypto;
        }

        public void setCrypto(final EncryptionJwtSigningJwtCryptographyProperties crypto) {
            this.crypto = crypto;
        }

        public RealmDefinition getRealm() {
            return realm;
        }

        public void setRealm(final RealmDefinition realm) {
            this.realm = realm;
        }

        public boolean isEncryptTokens() {
            return encryptTokens;
        }

        public void setEncryptTokens(final boolean encryptTokens) {
            this.encryptTokens = encryptTokens;
        }

        public String getSubjectNameIdFormat() {
            return subjectNameIdFormat;
        }

        public void setSubjectNameIdFormat(final String subjectNameIdFormat) {
            this.subjectNameIdFormat = subjectNameIdFormat;
        }

        public String getSigningKeystoreFile() {
            return signingKeystoreFile;
        }

        public void setSigningKeystoreFile(final String signingKeystoreFile) {
            this.signingKeystoreFile = signingKeystoreFile;
        }

        public String getSigningKeystorePassword() {
            return signingKeystorePassword;
        }

        public void setSigningKeystorePassword(final String signingKeystorePassword) {
            this.signingKeystorePassword = signingKeystorePassword;
        }

        public String getEncryptionKeystoreFile() {
            return encryptionKeystoreFile;
        }

        public void setEncryptionKeystoreFile(final String encryptionKeystoreFile) {
            this.encryptionKeystoreFile = encryptionKeystoreFile;
        }

        public String getEncryptionKeystorePassword() {
            return encryptionKeystorePassword;
        }

        public void setEncryptionKeystorePassword(final String encryptionKeystorePassword) {
            this.encryptionKeystorePassword = encryptionKeystorePassword;
        }

        public static class RealmDefinition implements Serializable {
            private static final long serialVersionUID = -2209230334376432934L;
            /**
             * Keystore path associated with the this realm.
             */
            private String keystoreFile;
            /**
             * Keystore password associated with the this realm.
             */
            private String keystorePassword;
            /**
             * Key alias associated with the this realm.
             */
            private String keystoreAlias;
            /**
             * Key alias associated with the this realm.
             */
            private String keyPassword;
            /**
             * Issuer/name of the realm identified and registered with STS.
             */
            private String issuer = "CAS";

            public String getKeyPassword() {
                return keyPassword;
            }

            public void setKeyPassword(final String keyPassword) {
                this.keyPassword = keyPassword;
            }

            public String getKeystoreFile() {
                return keystoreFile;
            }

            public void setKeystoreFile(final String keystoreFile) {
                this.keystoreFile = keystoreFile;
            }

            public String getKeystorePassword() {
                return keystorePassword;
            }

            public void setKeystorePassword(final String keystorePassword) {
                this.keystorePassword = keystorePassword;
            }

            public String getKeystoreAlias() {
                return keystoreAlias;
            }

            public void setKeystoreAlias(final String keystoreAlias) {
                this.keystoreAlias = keystoreAlias;
            }

            public String getIssuer() {
                return issuer;
            }

            public void setIssuer(final String issuer) {
                this.issuer = issuer;
            }
        }
    }
}
