DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS USERATTRS;

CREATE TABLE USERATTRS
(
    id        INT         AUTO_INCREMENT PRIMARY KEY NOT NULL,
    uid       VARCHAR(50) NOT NULL,
    attrname  VARCHAR(50) NOT NULL,
    attrvalue VARCHAR(50) NOT NULL
);

CREATE TABLE USERS
(
    id  INT         AUTO_INCREMENT PRIMARY KEY,
    uid VARCHAR(50) NOT NULL,
    psw VARCHAR(50) NOT NULL
);
