CREATE DATABASE audit;
GRANT ALL PRIVILEGES ON DATABASE audit TO postgres;

CREATE DATABASE saml;
GRANT ALL PRIVILEGES ON DATABASE saml TO postgres;

CREATE DATABASE services;
GRANT ALL PRIVILEGES ON DATABASE services TO postgres;

CREATE DATABASE tickets;
GRANT ALL PRIVILEGES ON DATABASE tickets TO postgres;

CREATE DATABASE pm;
GRANT ALL PRIVILEGES ON DATABASE pm TO postgres;

CREATE DATABASE yubikey;
GRANT ALL PRIVILEGES ON DATABASE yubikey TO postgres;

CREATE DATABASE mfa;
GRANT ALL PRIVILEGES ON DATABASE mfa TO postgres;

