CREATE DATABASE audit;
GRANT ALL PRIVILEGES ON DATABASE audit TO postgres;

CREATE DATABASE saml;
GRANT ALL PRIVILEGES ON DATABASE saml TO postgres;

CREATE DATABASE services;
GRANT ALL PRIVILEGES ON DATABASE services TO postgres;

CREATE DATABASE tickets;
GRANT ALL PRIVILEGES ON DATABASE tickets TO postgres;

CREATE DATABASE pm;
GRANT ALL PRIVILEGES ON DATABASE pm TO postgres;

CREATE DATABASE yubikey;
GRANT ALL PRIVILEGES ON DATABASE yubikey TO postgres;

CREATE DATABASE mfa;
GRANT ALL PRIVILEGES ON DATABASE mfa TO postgres;

CREATE DATABASE oidc;
GRANT ALL PRIVILEGES ON DATABASE oidc TO postgres;

CREATE DATABASE oauth;
GRANT ALL PRIVILEGES ON DATABASE oauth TO postgres;

CREATE DATABASE casconfig;
GRANT ALL PRIVILEGES ON DATABASE casconfig TO postgres;

CREATE DATABASE webapp;
GRANT ALL PRIVILEGES ON DATABASE webapp TO postgres;

CREATE DATABASE users;
GRANT ALL PRIVILEGES ON DATABASE users TO postgres;

CREATE DATABASE impersonation;
GRANT ALL PRIVILEGES ON DATABASE impersonation TO postgres;

CREATE DATABASE events;
GRANT ALL PRIVILEGES ON DATABASE events TO postgres;
