
package org.apereo.cas;

import org.apereo.cas.adaptors.x509.web.extractcert.X509CertificateExtractorTests;
import org.apereo.cas.adaptors.x509.web.flow.X509CertificateCredentialsNonInteractiveActionTests;
import org.apereo.cas.adaptors.x509.web.flow.X509CertificateCredentialsRequestHeaderActionTests;

import org.junit.platform.suite.api.SelectClasses;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@SelectClasses({
    X509CertificateExtractorTests.class,
    X509CertificateCredentialsNonInteractiveActionTests.class,
    X509CertificateCredentialsRequestHeaderActionTests.class
})
public class AllTestsSuite {
}
