
package org.apereo.cas;

import org.apereo.cas.support.saml.web.idp.audit.SamlRequestAuditResourceResolverTests;
import org.apereo.cas.support.saml.web.idp.audit.SamlResponseAuditPrincipalIdProviderTests;
import org.apereo.cas.support.saml.web.idp.audit.SamlResponseAuditResourceResolverTests;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@RunWith(Suite.class)
@Suite.SuiteClasses({
    SamlRequestAuditResourceResolverTests.class,
    SamlResponseAuditPrincipalIdProviderTests.class,
    SamlResponseAuditResourceResolverTests.class
})
public class AllTestsSuite {
}
