
package org.apereo.cas;

import org.apereo.cas.web.RegisteredServiceResponseHeadersEnforcementFilterTests;
import org.apereo.cas.web.SimpleUrlValidatorFactoryBeanTests;

import org.junit.platform.suite.api.SelectClasses;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@SelectClasses({
    RegisteredServiceResponseHeadersEnforcementFilterTests.class,
    SimpleUrlValidatorFactoryBeanTests.class
})
public class AllTestsSuite {
}
