
package org.apereo.cas;

import org.apereo.cas.configuration.support.CasConfigurationJasyptCipherExecutorTests;
import org.apereo.cas.configuration.support.DefaultCasConfigurationPropertiesSourceLocatorTests;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@RunWith(Suite.class)
@Suite.SuiteClasses({
    CasConfigurationJasyptCipherExecutorTests.class,
    DefaultCasConfigurationPropertiesSourceLocatorTests.class
})
public class AllTestsSuite {
}
