
package org.apereo.cas;

import org.apereo.cas.configuration.support.CasConfigurationJasyptCipherExecutorTests;
import org.apereo.cas.configuration.support.DefaultCasConfigurationPropertiesSourceLocatorTests;

import org.junit.platform.runner.JUnitPlatform;
import org.junit.platform.suite.api.SelectClasses;
import org.junit.runner.RunWith;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@SelectClasses({
    CasConfigurationJasyptCipherExecutorTests.class,
    DefaultCasConfigurationPropertiesSourceLocatorTests.class
})
@RunWith(JUnitPlatform.class)
public class AllTestsSuite {
}
