//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.13 at 11:12:37 PM IRST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://apereo.org/cas", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.apereo.cas.authentication.soap;
