
package org.apereo.cas;

import org.apereo.cas.clouddirectory.DefaultCloudDirectoryRepositoryTests;
import org.apereo.cas.authentication.CloudDirectoryAuthenticationHandlerTests;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@RunWith(Suite.class)
@Suite.SuiteClasses({
    DefaultCloudDirectoryRepositoryTests.class,
    CloudDirectoryAuthenticationHandlerTests.class
})
public class AllTestsSuite {
}
