
package org.apereo.cas;

import org.apereo.cas.services.util.CasAddonsRegisteredServicesJsonSerializerTests;
import org.apereo.cas.services.util.RegisteredServicePublicKeyCipherExecutorTests;

import org.junit.platform.suite.api.SelectClasses;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@SelectClasses({
    RegisteredServicePublicKeyCipherExecutorTests.class,
    CasAddonsRegisteredServicesJsonSerializerTests.class
})
public class AllTestsSuite {
}
