
package org.apereo.cas;

import org.apereo.cas.services.util.CasAddonsRegisteredServicesJsonSerializerTests;
import org.apereo.cas.services.util.RegisteredServiceAccessStrategyAuditableEnforcerTests;
import org.apereo.cas.services.util.RegisteredServiceNoOpCipherExecutorTests;
import org.apereo.cas.services.util.RegisteredServicePublicKeyCipherExecutorTests;

import org.junit.platform.runner.JUnitPlatform;
import org.junit.platform.suite.api.SelectClasses;
import org.junit.runner.RunWith;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@SelectClasses({
    RegisteredServicePublicKeyCipherExecutorTests.class,
    CasAddonsRegisteredServicesJsonSerializerTests.class,
    RegisteredServiceAccessStrategyAuditableEnforcerTests.class,
    RegisteredServiceNoOpCipherExecutorTests.class
})
@RunWith(JUnitPlatform.class)
public class AllTestsSuite {
}
