
package org.apereo.cas;

import org.apereo.cas.support.saml.idp.metadata.CouchDbSamlIdPMetadataGeneratorTests;
import org.apereo.cas.support.saml.metadata.resolver.CouchDbSamlRegisteredServiceMetadataResolverTests;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@RunWith(Suite.class)
@Suite.SuiteClasses({
    CouchDbSamlIdPMetadataGeneratorTests.class,
    CouchDbSamlRegisteredServiceMetadataResolverTests.class
})
public class AllTestsSuite {
}
