
package org.apereo.cas;

import org.apereo.cas.support.saml.idp.metadata.CouchDbSamlIdPMetadataGeneratorTests;
import org.apereo.cas.support.saml.metadata.resolver.CouchDbSamlRegisteredServiceMetadataResolverTests;

import org.junit.platform.suite.api.SelectClasses;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@SelectClasses({
    CouchDbSamlIdPMetadataGeneratorTests.class,
    CouchDbSamlRegisteredServiceMetadataResolverTests.class
})
public class AllTestsSuite {
}
