
package org.apereo.cas;

import org.apereo.cas.JdbcMultiRowAttributeRepositoryTests;
import org.apereo.cas.JdbcSingleRowAttributeRepositoryTests;
import org.apereo.cas.RestfulPersonAttributeDaoTests;
import org.apereo.cas.CachingAttributeRepositoryTests;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@RunWith(Suite.class)
@Suite.SuiteClasses({
    JdbcMultiRowAttributeRepositoryTests.class,
    JdbcSingleRowAttributeRepositoryTests.class,
    RestfulPersonAttributeDaoTests.class,
    CachingAttributeRepositoryTests.class
})
public class AllTestsSuite {
}
