
package org.apereo.cas;

import org.junit.platform.suite.api.SelectClasses;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@SelectClasses({
    JdbcMultiRowAttributeRepositoryTests.class,
    JdbcSingleRowAttributeRepositoryTests.class,
    RestfulPersonAttributeDaoTests.class,
    CachingAttributeRepositoryTests.class,
    JdbcSingleRowAttributeRepositoryPostgresTests.class
})
public class AllTestsSuite {
}
