
package org.apereo.cas;

import org.apereo.cas.authentication.support.GroovyPasswordPolicyHandlingStrategyTests;
import org.apereo.cas.authentication.support.OptionalWarningLdapAccountStateHandlerTests;
import org.apereo.cas.authentication.support.RejectResultCodeLdapPasswordPolicyHandlingStrategyTests;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@RunWith(Suite.class)
@Suite.SuiteClasses({
    GroovyPasswordPolicyHandlingStrategyTests.class,
    OptionalWarningLdapAccountStateHandlerTests.class,
    RejectResultCodeLdapPasswordPolicyHandlingStrategyTests.class
})
public class AllTestsSuite {
}
