
package org.apereo.cas;

import org.apereo.cas.ticket.registry.DynamoDbTicketRegistryWithoutEncryptionTests;
import org.apereo.cas.ticket.registry.DynamoDbTicketRegistryFacilitatorTests;
import org.apereo.cas.ticket.registry.DynamoDbTicketRegistryWithEncryptionTests;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@RunWith(Suite.class)
@Suite.SuiteClasses({
    DynamoDbTicketRegistryWithoutEncryptionTests.class,
    DynamoDbTicketRegistryFacilitatorTests.class,
    DynamoDbTicketRegistryWithEncryptionTests.class
})
public class AllTestsSuite {
}
