
package org.apereo.cas;

import org.apereo.cas.ticket.registry.DynamoDbTicketRegistryFacilitatorTests;
import org.apereo.cas.ticket.registry.DynamoDbTicketRegistryWithEncryptionTests;
import org.apereo.cas.ticket.registry.DynamoDbTicketRegistryWithoutEncryptionTests;

import org.junit.platform.suite.api.SelectClasses;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@SelectClasses({
    DynamoDbTicketRegistryWithoutEncryptionTests.class,
    DynamoDbTicketRegistryFacilitatorTests.class,
    DynamoDbTicketRegistryWithEncryptionTests.class
})
public class AllTestsSuite {
}
