
package org.apereo.cas;

import org.apereo.cas.ticket.registry.DynamoDbTicketRegistryFacilitatorTests;
import org.apereo.cas.ticket.registry.DynamoDbTicketRegistryTests;

import org.junit.platform.suite.api.SelectClasses;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@SelectClasses({
    DynamoDbTicketRegistryFacilitatorTests.class,
    DynamoDbTicketRegistryTests.class
})
public class AllTestsSuite {
}
