
package org.apereo.cas;

import org.apereo.cas.web.flow.decorator.GroovyLoginWebflowDecoratorTests;
import org.apereo.cas.web.flow.decorator.RestfulLoginWebflowDecoratorTests;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@RunWith(Suite.class)
@Suite.SuiteClasses({
    GroovyLoginWebflowDecoratorTests.class,
    RestfulLoginWebflowDecoratorTests.class
})
public class AllTestsSuite {
}
