package org.apereo.cas;

import org.apereo.cas.aup.JdbcAcceptableUsagePolicyRepositoryAdvancedTests;
import org.apereo.cas.aup.JdbcAcceptableUsagePolicyRepositoryTests;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@RunWith(Suite.class)
@Suite.SuiteClasses({
    JdbcAcceptableUsagePolicyRepositoryAdvancedTests.class,
    JdbcAcceptableUsagePolicyRepositoryTests.class
})
public class AllTestsSuite {
}
