
package org.apereo.cas;

import org.apereo.cas.adaptors.yubikey.web.flow.YubiKeyAccountSaveRegistrationActionTests;
import org.apereo.cas.adaptors.yubikey.web.flow.YubiKeyAccountCheckRegistrationActionTests;
import org.apereo.cas.adaptors.yubikey.DefaultYubiKeyAccountValidatorTests;
import org.apereo.cas.adaptors.yubikey.AcceptAllYubiKeyAccountValidatorTests;
import org.apereo.cas.adaptors.yubikey.DenyAllYubiKeyAccountValidatorTests;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@RunWith(Suite.class)
@Suite.SuiteClasses({
    YubiKeyAccountSaveRegistrationActionTests.class,
    YubiKeyAccountCheckRegistrationActionTests.class,
    DefaultYubiKeyAccountValidatorTests.class,
    AcceptAllYubiKeyAccountValidatorTests.class,
    DenyAllYubiKeyAccountValidatorTests.class
})
public class AllTestsSuite {
}
