
package org.apereo.cas;

import org.apereo.cas.adaptors.u2f.U2FAuthenticationHandlerTests;
import org.apereo.cas.adaptors.u2f.storage.U2FGroovyResourceDeviceRepositoryTests;
import org.apereo.cas.adaptors.u2f.storage.U2FInMemoryDeviceRepositoryTests;
import org.apereo.cas.adaptors.u2f.storage.U2FJsonResourceDeviceRepositoryTests;
import org.apereo.cas.adaptors.u2f.storage.U2FRestResourceDeviceRepositoryTests;

import org.junit.platform.suite.api.SelectClasses;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@SelectClasses({
    U2FRestResourceDeviceRepositoryTests.class,
    U2FGroovyResourceDeviceRepositoryTests.class,
    U2FJsonResourceDeviceRepositoryTests.class,
    U2FInMemoryDeviceRepositoryTests.class,
    U2FAuthenticationHandlerTests.class
})
public class AllTestsSuite {
}
