
package org.apereo.cas;

import org.apereo.cas.interrupt.GroovyScriptInterruptInquirerTests;
import org.apereo.cas.interrupt.JsonResourceInterruptInquirerTests;
import org.apereo.cas.interrupt.RegexAttributeInterruptInquirerTests;
import org.apereo.cas.interrupt.RestEndpointInterruptInquirerTests;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@RunWith(Suite.class)
@Suite.SuiteClasses({
    RegexAttributeInterruptInquirerTests.class,
    GroovyScriptInterruptInquirerTests.class,
    JsonResourceInterruptInquirerTests.class,
    RestEndpointInterruptInquirerTests.class
})
public class AllTestsSuite {
}
