
package org.apereo.cas;

import org.apereo.cas.grouper.services.GrouperRegisteredServiceAccessStrategyTests;
import org.apereo.cas.web.flow.GrouperMultifactorAuthenticationPolicyEventResolverTests;

import org.junit.platform.suite.api.SelectClasses;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@SelectClasses({
    GrouperMultifactorAuthenticationPolicyEventResolverTests.class,
    GrouperRegisteredServiceAccessStrategyTests.class
})
public class AllTestsSuite {
}
