
package org.apereo.cas;

import org.apereo.cas.web.DefaultTokenRequestExtractorTests;
import org.apereo.cas.web.flow.TokenAuthenticationActionTests;

import org.junit.platform.suite.api.SelectClasses;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@SelectClasses({
    DefaultTokenRequestExtractorTests.class,
    TokenAuthenticationActionTests.class
})
public class AllTestsSuite {
}
