
package org.apereo.cas;

import org.apereo.cas.aws.AmazonEnvironmentAwareClientBuilderTests;
import org.apereo.cas.aws.ChainingAWSCredentialsProviderTests;

import org.junit.platform.suite.api.SelectClasses;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@SelectClasses({
    AmazonEnvironmentAwareClientBuilderTests.class,
    ChainingAWSCredentialsProviderTests.class
})
public class AllTestsSuite {
}
