
package org.apereo.cas;

import org.apereo.cas.digest.DefaultDigestHashedCredentialRetrieverTests;
import org.apereo.cas.digest.DigestCredentialTests;
import org.apereo.cas.digest.util.DigestAuthenticationUtilsTests;

import org.junit.platform.suite.api.SelectClasses;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@SelectClasses({
    DigestAuthenticationUtilsTests.class,
    DefaultDigestHashedCredentialRetrieverTests.class,
    DigestCredentialTests.class
})
public class AllTestsSuite {
}
