
package org.apereo.cas;

import org.apereo.cas.digest.util.DigestAuthenticationUtilsTests;
import org.apereo.cas.digest.DefaultDigestHashedCredentialRetrieverTests;
import org.apereo.cas.digest.DigestCredentialTests;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@RunWith(Suite.class)
@Suite.SuiteClasses({
    DigestAuthenticationUtilsTests.class,
    DefaultDigestHashedCredentialRetrieverTests.class,
    DigestCredentialTests.class
})
public class AllTestsSuite {
}
