
package org.apereo.cas;

import org.apereo.cas.aup.DefaultAcceptableUsagePolicyRepositoryTests;
import org.apereo.cas.web.flow.AcceptableUsagePolicySubmitActionTests;
import org.apereo.cas.web.flow.AcceptableUsagePolicyVerifyActionTests;

import org.junit.platform.suite.api.SelectClasses;

/**
 * This is {@link AllTestsSuite}.
 *
 * @author Auto-generated by Gradle Build
 * @since 6.0.0-RC3
 */
@SelectClasses({
    AcceptableUsagePolicySubmitActionTests.class,
    AcceptableUsagePolicyVerifyActionTests.class,
    DefaultAcceptableUsagePolicyRepositoryTests.class
})
public class AllTestsSuite {
}
